# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
image-version: stable

name: bazzite-dx-nvidia-custom
description: "Bazzite DX NVIDIA stable + Discover integrations + snap + podman compose & podman-compose + Nix daemon with /nix bind-mounted to /var/nix (signed)"
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia

modules:
  - type: script
    scripts:
      - 05-terra-enable.sh

  - type: dnf
    install:
      packages:
        - plasma-discover
        - plasma-discover-flatpak
        - plasma-discover-kns
        - plasma-discover-notifier
        - plasma-discover-offline-updates
        - plasma-discover-packagekit
        - plasma-discover-rpm-ostree
        - plasma-discover-snap

        - podman
        - podman-compose

        - repo: terra
          packages:
            - opensnitch

        - snapd

        - nix
        - nix-daemon

        - curl
        - ca-certificates
        - git
        - xz
        - bzip2
        - gzip
        - tar
        - openssl
        - shadow-utils

  - type: script
    scripts:
      - 85-terra-disable.sh
      - 10-nix-bind-mount.sh
      - 20-nix-selinux.sh
      - 30-run0-selinux-workarounds.sh
      - 90-cleanup.sh
